package org.imooc.mall.dao;

import org.apache.ibatis.annotations.Param;
import org.imooc.mall.pojo.Shipping;

import java.util.List;
import java.util.Map;
import java.util.Set;

public interface ShippingMapper {
    List<Shipping> selectByIdSet(@Param("idSet") Set idSet);
    int deleteByIdAndUid(@Param("uid") Integer uid,
                         @Param("shippingId")Integer shippingId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated
     */
    int insertSelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Shipping record);


    List<Shipping> selectByUid(Integer uid);

    Shipping selectByUidAndShippingId(Integer uid,Integer shippingid);
}