package org.imooc.mall.dao;

import org.apache.ibatis.annotations.Param;
import org.imooc.mall.pojo.OrderItme;

import java.util.List;
import java.util.Set;

public interface OrderItmeMapper {
    List<OrderItme> selectByOrderNoSet(@Param("orderNoSet") Set orderNoSet);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_itme
     *
     * @mbg.generated
     */
    int batchSelective(@Param("orderItemList") List<OrderItme> recordList);
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_itme
     *
     * @mbg.generated
     */
    int insert(OrderItme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_itme
     *
     * @mbg.generated
     */
    int insertSelective(OrderItme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_itme
     *
     * @mbg.generated
     */
    OrderItme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_itme
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderItme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_itme
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderItme record);
}