package org.imooc.mall.pojo;

import lombok.Data;

import java.util.Date;
@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.id
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.username
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
   ; private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.password
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.email
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.question
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.answer
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.role
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.creatime_time
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    private Date creatimeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_user.update_time
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.id
     *
     * @return the value of mall_user.id
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public User(){
    }
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.id
     *
     * @param id the value for mall_user.id
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.username
     *
     * @return the value of mall_user.username
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.username
     *
     * @param username the value for mall_user.username
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.password
     *
     * @return the value of mall_user.password
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.password
     *
     * @param password the value for mall_user.password
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.email
     *
     * @return the value of mall_user.email
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.email
     *
     * @param email the value for mall_user.email
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.question
     *
     * @return the value of mall_user.question
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.question
     *
     * @param question the value for mall_user.question
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.answer
     *
     * @return the value of mall_user.answer
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.answer
     *
     * @param answer the value for mall_user.answer
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.role
     *
     * @return the value of mall_user.role
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.role
     *
     * @param role the value for mall_user.role
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.creatime_time
     *
     * @return the value of mall_user.creatime_time
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public Date getCreatimeTime() {
        return creatimeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.creatime_time
     *
     * @param creatimeTime the value for mall_user.creatime_time
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public void setCreatimeTime(Date creatimeTime) {
        this.creatimeTime = creatimeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_user.update_time
     *
     * @return the value of mall_user.update_time
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_user.update_time
     *
     * @param updateTime the value for mall_user.update_time
     *
     * @mbg.generated Wed Mar 16 23:03:48 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}